import { useState, useEffect } from "react";

import { useChat } from "../../context/ChatContext";

import ModelSelector from "./ModelSelector";
// import AttachButton from "./AttachButton";
import MessageInput from "./MessageInput";
import VoiceButton from "./VoiceButton";
import SendButton from "./SendButton";

import type { Provider } from "../../types/chat";

interface ChatInputProps {
  variant: "center" | "bottom";
  initialMessage?: string;
}

export default function ChatInput({
  variant,
  initialMessage = "",
}: ChatInputProps) {
  const { send, loading } = useChat();

  const [provider, setProvider] = useState<Provider>("gemini");
  const [message, setMessage] = useState(initialMessage);

  useEffect(() => {
    if (initialMessage) {
      setMessage(initialMessage);
    }
  }, [initialMessage]);

  const handleSend = async () => {
    const text = message.trim();

    if (!text) return;

    await send(text, provider);
    setMessage("");
  };

  return (
    <div
      className={
        variant === "center"
          ? "w-full transition-all duration-500"
          : "sticky bottom-0 left-0 right-0 border-t border-white/10 bg-[#0B0F19]/90 backdrop-blur-2xl p-4 sm:p-6 transition-all duration-500 z-20"
      }
    >
      <div
        className={
          variant === "center"
            ? "mx-auto w-full max-w-2xl"
            : "mx-auto w-full max-w-4xl"
        }
      >
        <div
          className="
            flex
            items-center
            gap-2.5
            rounded-2xl
            border
            border-white/10
            bg-[#0F1626]/80
            p-2.5
            sm:p-3
            shadow-2xl
            backdrop-blur-xl
            transition-all
            duration-300
            focus-within:border-red-500/50
            focus-within:shadow-[0_0_30px_-5px_rgba(225,29,72,0.2)]
          "
        >
          <ModelSelector provider={provider} onChange={setProvider} />

          {/* <AttachButton /> */}

          <div className="flex-1 min-w-0">
            <MessageInput
              value={message}
              onChange={setMessage}
              onSend={handleSend}
              disabled={loading}
            />
          </div>

          <VoiceButton />

          <SendButton
            disabled={!message.trim()}
            loading={loading}
            onClick={handleSend}
          />
        </div>

        {variant === "bottom" && (
          <p className="mt-2 text-center text-[11px] text-slate-500">
            WebAndCrafts AI • Empowering enterprise intelligence. Responses may be generated by Gemini or Groq models.
          </p>
        )}
      </div>
    </div>
  );
}